### ISSUE TITLE
Please change bugtracker link

### ISSUE THREAD

**Issue by pcav** [riccardoklinger/amaps#9]
It currently points to the repo, not to the issues page.
Thanks.

**Comment by riccardoklinger** [comment]
Hi @pcav , just checked again the uploaded version. this looks right to me. could you confirm? 
![current issue tracker in metadata](https://user-images.githubusercontent.com/7377897/58431985-8ece6080-80b0-11e9-94b4-01da4d48c9f9.png)

**Comment by pcav** [comment]
Sorry, wrong ticket.
